export const COLLEGE_GATE = {
  id: "gate",
  label: "College Gate",
  lat: 12.872848666834663,
  lng: 80.22596731088542,
  type: "user_location" as const,
  color: "#3b82f6",
};

export const CAMPUS_LOCATIONS = [
  {
    id: "admin",
    label: "Administration Block",
    lat: 12.873295385872186,
    lng: 80.22168752570319,
    color: "#38bdf8",
    icon: "🏛️",
    searchTerms: ["admin", "administration", "office", "block", "registrar", "principal"],
    category: "admin",
    floors: 4,
    height: 18,
    architecturalStyle: "Modernist Colonnade & Concrete Facade",
    hours: "08:30 AM – 05:30 PM",
    amenities: ["Admissions Desk", "Registrar Office", "Student Affairs", "Ramp Access", "Restrooms"],
    description: "Primary institutional headquarters housing admissions, student affairs, and administrative services.",
    floorLevels: [
      { level: 0, label: "Ground", name: "Main Portico & Admissions", facilities: ["Welcome Desk", "Fee Counter", "Accessible Ramp Entrance"] },
    ],
  },
  {
    id: "library",
    label: "Central Library",
    lat: 12.873387474047385,
    lng: 80.21920382817343, // ⚠️ VERIFIED: 80.xxx NOT 0.xxx
    color: "#06b6d4",
    icon: "📚",
    searchTerms: ["library", "central library", "books", "study", "reading", "journals", "research"],
    category: "academic",
    floors: 2,
    height: 11,
    architecturalStyle: "Two-Storey Complex with Portico & Landscaped Garden",
    hours: "08:00 AM – 10:00 PM",
    amenities: ["150,000+ Volumes", "Digital Learning Commons", "Digital Research Journals", "Air-Conditioned Reading Halls", "Wheelchair Ramp"],
    description: "Dedicated central learning resource center surrounded by landscaped gardens, housing print stacks, digital research commons, and study spaces.",
    floorLevels: [
      { level: 0, label: "Ground", name: "Main Circulation & Digital Commons", facilities: ["Circulation Desk", "Digital Resource Center (150+ PCs)", "OPAC Kiosks", "Periodicals Lounge", "Front Garden Walkway"] },
      { level: 1, label: "Floor 1", name: "Main Reference Stacks & Reading Hall", facilities: ["Engineering & Science Stacks", "Quiet Study Hall (1200+ Seats)", "Research Scholar Cubicles", "Thesis Archive"] },
    ],
  },
  {
    id: "basketball",
    label: "Basketball Courts",
    lat: 12.871519179799405,
    lng: 80.22023647077431,
    color: "#f59e0b",
    icon: "🏀",
    searchTerms: ["basketball", "courts", "sports", "ground", "athletics", "gym"],
    category: "athletics",
    floors: 1,
    height: 9,
    architecturalStyle: "Dual Regulation Hardcourt Complex",
    hours: "06:00 AM – 09:00 PM",
    amenities: ["Synthetic Polyurethane Flooring", "LED Floodlights", "Bleachers", "First-Aid Station", "Hydration Point"],
    description: "Dual standard FIBA regulation outdoor basketball courts with shock-absorbing surfaces and evening lighting rigs.",
    floorLevels: [
      { level: 0, label: "Court Level", name: "Main Hardcourt Surface", facilities: ["Court A (Varsity)", "Court B (Practice)", "Equipment Desk", "Bleachers", "Hydration Station"] },
    ],
  },
  {
    id: "canteen",
    label: "Central Canteen",
    lat: 12.872644437281318,
    lng: 80.21958245523395,
    color: "#9bffce",
    icon: "🍽️",
    searchTerms: ["canteen", "food", "cafeteria", "mess", "dining", "snacks", "appa mess"],
    category: "dining",
    floors: 2,
    height: 12,
    architecturalStyle: "High-Capacity Dining Hall Complex & Student Food Court",
    hours: "07:00 AM – 08:30 PM",
    amenities: ["Mega Dining Hall", "Stainless Steel Seating", "Perimeter Handwash Troughs", "Snack Counters", "Accessible Entrance"],
    description: "Iconic Sathyabama dining infrastructure providing daily meals and refreshments for thousands of students and faculty.",
    floorLevels: [
      { level: 0, label: "Ground", name: "Central Dining Mess (Appa Mess)", facilities: ["Mega Dining Hall", "Multi-lane Buffet Counters", "Perimeter Handwash Troughs", "Commercial Steam Kitchen"] },
      { level: 1, label: "Floor 1", name: "Student Canteen & Refreshment Deck", facilities: ["Snack & Food Counters", "Fresh Juice & Coffee Bar", "Bakery & Ice Cream Kiosk"] },
    ],
  },
] as const;
